In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score , confusion_matrix,classification_report


In [2]:
df = pd.read_csv('/kaggle/input/iris/Iris.csv',index_col =0)

In [3]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
X,y = df.iloc[:,0:-1],df.iloc[:,-1]

In [5]:
label = LabelEncoder()
y = label.fit_transform(y)

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [7]:
cl = LogisticRegression(max_iter=1000)

In [8]:
cl.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [9]:
accuracy_score(y_test,cl.predict(X_test))

0.9666666666666667

In [10]:
print(confusion_matrix(y_test,cl.predict(X_test)))

[[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]


In [11]:
print(classification_report(y_test,cl.predict(X_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.88      0.93         8
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30



In [12]:
X_test

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Id                                                           
7              4.6           3.4            1.4           0.3
4              4.6           3.1            1.5           0.2
114            5.7           2.5            5.0           2.0
13             4.8           3.0            1.4           0.1
25             4.8           3.4            1.9           0.2
130            7.2           3.0            5.8           1.6
26             5.0           3.0            1.6           0.2
109            6.7           2.5            5.8           1.8
129            6.4           2.8            5.6           2.1
46             4.8           3.0            1.4           0.3
49             5.3           3.7            1.5           0.2
43             4.4           3.2            1.3           0.2
36             5.0           3.2            1.2           0.2
6              5.4           3.9            1.7           0.4
86             6.0           3.4            4.5           1.6
55             6.5           2.8            4.6           1.5
42             4.5           2.3            1.3           0.3
97             5.7           2.9            4.2           1.3
145            6.7           3.3            5.7           2.5
90             5.5           2.5            4.0           1.3
78             6.7           3.0            5.0           1.7
75             6.4           2.9            4.3           1.3
116            6.4           3.2            5.3           2.3
95             5.6           2.7            4.2           1.3
88             6.3           2.3            4.4           1.3
30             4.7           3.2            1.6           0.2
3              4.7           3.2            1.3           0.2
128            6.1           3.0            4.9           1.8
45             5.1           3.8            1.9           0.4
126            7.2           3.2            6.0           1.8

In [13]:

cl.predict_proba([[5,3,1,0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([[9.82170517e-01, 1.78294737e-02, 9.76378559e-09]])

In [14]:
cl.predict([[5,3,1,0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [15]:
X.shape

(150, 4)

In [16]:
y.shape

(150,)